project_id = "bczqebeixeunhzpisurh"

[functions.enviar-email-pedido]
verify_jwt = false

[functions.sancet-webhook-asaas]
verify_jwt = false

[functions.sancet-cadastrar-paciente]
verify_jwt = false

[functions.sancet-primeiro-acesso]
verify_jwt = false

[functions.sancet-contato-email]
verify_jwt = false
