-- =====================================================================
-- Central de Ajuda — tabela + RLS + TODOS os tutoriais.
-- Rode este script UMA vez no Supabase (SQL Editor), projeto bczqebeixeunhzpisurh.
-- Idempotente: pode rodar de novo sem duplicar (ON CONFLICT DO NOTHING).
-- =====================================================================

create table if not exists public.tutoriais (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  titulo text not null,
  categoria text,
  ordem integer not null default 0,
  resumo text,
  conteudo_html text not null default '',
  publicado boolean not null default true,
  atualizado_em timestamptz not null default now(),
  criado_em timestamptz not null default now()
);
create index if not exists idx_tutoriais_categoria on public.tutoriais (categoria);
create index if not exists idx_tutoriais_ordem on public.tutoriais (categoria, ordem);

alter table public.tutoriais enable row level security;
grant select on public.tutoriais to authenticated;
grant insert, update, delete on public.tutoriais to authenticated;

drop policy if exists "tutoriais_select" on public.tutoriais;
create policy "tutoriais_select" on public.tutoriais for select to authenticated
  using (
    public.has_role(auth.uid(), 'admin'::app_role)
    or public.has_role(auth.uid(), 'staff'::app_role)
  );

drop policy if exists "tutoriais_write" on public.tutoriais;
create policy "tutoriais_write" on public.tutoriais for all to authenticated
  using (public.has_role(auth.uid(), 'admin'::app_role))
  with check (public.has_role(auth.uid(), 'admin'::app_role));

insert into public.tutoriais (slug, titulo, categoria, ordem, resumo, conteudo_html) values
('primeiros-passos', 'Primeiros passos no painel', 'Primeiros passos', 1, 'Visão geral do painel interno e onde fica cada coisa.', '<p>Bem-vindo ao painel interno da Sancet. No menu à esquerda você encontra:</p><ul><li><strong>Visão Geral</strong> — resumo do dia.</li><li><strong>Pedidos</strong> e <strong>Check-in</strong> — agendamentos e recepção.</li><li><strong>Pacientes, Catálogo, Unidades, Convênios</strong> — dados de cadastro.</li><li><strong>Configurações</strong> — aparência, e-mail, Shift e LGPD.</li><li><strong>Sites</strong> — páginas, landing pages e blog.</li><li><strong>Equipe</strong> — usuários e permissões.</li><li><strong>Ajuda</strong> — estes tutoriais.</li></ul><p>Alguns itens (Sites, Equipe) só aparecem para administradores.</p>'),
('papeis-permissoes', 'Administrador x Equipe: papéis e permissões', 'Primeiros passos', 2, 'A diferença entre os dois níveis de acesso e o que cada um enxerga.', '<p>Há dois níveis de acesso:</p><ul><li><strong>Administrador</strong> — vê e edita tudo, incluindo Sites, Equipe, Configurações e a edição desta Central de Ajuda.</li><li><strong>Equipe (staff)</strong> — usa o dia a dia (pedidos, check-in, pacientes, catálogo) conforme as permissões que o admin definir.</li></ul><p>As permissões de cada membro são definidas em <strong>Equipe</strong>. Um membro também pode ser vinculado a unidades específicas.</p>'),
('usar-visao-geral', 'Acompanhar o dia na Visão Geral', 'Visão Geral', 5, 'Os números e atalhos da tela inicial do painel.', '<p>A <strong>Visão Geral</strong> é a primeira tela ao entrar. Nela você acompanha:</p><ul><li>Pedidos do dia e quantos estão em cada etapa.</li><li>Pendências que precisam de atenção.</li></ul><p>O selo vermelho ao lado de <strong>Pedidos</strong>, no menu, mostra quantos pedidos novos aguardam atendimento.</p>'),
('lista-pedidos-filtros', 'Lista de pedidos: buscar e filtrar', 'Pedidos & CRM', 10, 'Encontrar um pedido por nome, protocolo, status ou data.', '<p>Em <strong>Pedidos</strong>, a visão em lista permite:</p><ol><li>Buscar por nome do paciente ou protocolo.</li><li>Filtrar por status (Novo, Em análise, Confirmado, etc.).</li><li>Abrir um pedido clicando na linha para ver todos os detalhes.</li></ol><p>Use o botão de alternância para trocar entre <strong>Lista</strong> e <strong>Kanban</strong>.</p>'),
('gerenciar-pedidos-kanban', 'Gerenciar pedidos no Kanban', 'Pedidos & CRM', 11, 'Mover pedidos entre etapas arrastando os cartões.', '<p>No <strong>Kanban</strong>, cada cartão é um pedido e cada coluna é uma etapa.</p><ol><li>Arraste um cartão de uma coluna para outra para mudar o status.</li><li>Os contadores no topo mostram quantos pedidos há em cada etapa.</li><li>Clique no cartão para abrir os detalhes e os documentos enviados.</li></ol><p>A escolha entre Lista e Kanban fica salva no seu navegador.</p>'),
('status-pedido-etapas', 'As etapas de um pedido', 'Pedidos & CRM', 12, 'O que significa cada status, do agendamento à conclusão.', '<p>Um pedido percorre estas etapas:</p><ol><li><strong>Novo</strong> — acabou de ser agendado pelo paciente.</li><li><strong>Em análise</strong> — a equipe está conferindo dados e documentos.</li><li><strong>Aguardando pagamento</strong> — falta a confirmação do pagamento.</li><li><strong>Confirmado</strong> — tudo certo, agendamento válido.</li><li><strong>Concluído</strong> — atendimento realizado.</li><li><strong>Cancelado</strong> — pedido cancelado.</li></ol>'),
('detalhes-pedido-documentos', 'Ver detalhes e documentos do pedido', 'Pedidos & CRM', 13, 'Conferir exames, dados do paciente e anexos enviados.', '<p>Ao abrir um pedido você vê:</p><ul><li>Os exames escolhidos e a unidade/data do agendamento.</li><li>Os dados do paciente e do convênio (quando houver).</li><li>Os <strong>documentos anexados</strong> (RG, pedido médico, carteirinha, receita, etc.).</li></ul><p>Confira se os documentos obrigatórios foram enviados antes de confirmar o pedido.</p>'),
('confirmar-pagamento', 'Confirmar pagamento manualmente', 'Pedidos & CRM', 14, 'Marcar um pedido como pago quando o pagamento é feito fora do sistema.', '<p>Quando o pagamento é feito presencialmente ou por outro meio:</p><ol><li>Abra o pedido em <strong>Aguardando pagamento</strong>.</li><li>Use a opção de <strong>confirmar pagamento</strong>.</li><li>O pedido passa para <strong>Confirmado</strong>.</li></ol>'),
('checkin-qr', 'Check-in por QR Code na recepção', 'Check-in', 20, 'Registrar a chegada do paciente lendo o QR do voucher.', '<p>Na recepção, use <strong>Check-in</strong> para registrar a chegada:</p><ol><li>Peça o voucher do paciente (impresso ou na tela do celular).</li><li>Leia o <strong>QR Code</strong> com a câmera ou com o leitor da própria tela.</li><li>O pedido aparece na hora para conferência.</li></ol><p>Avisos em amarelo indicam documentos pendentes; em verde, tudo certo.</p>'),
('gerenciar-pacientes', 'Consultar e editar pacientes', 'Pacientes', 25, 'Buscar um paciente e atualizar seus dados de cadastro.', '<p>Em <strong>Pacientes</strong> você consulta e edita os cadastros:</p><ol><li>Busque por nome ou CPF.</li><li>Abra o cadastro para ver e corrigir dados (contato, endereço).</li></ol><p>Todo acesso a dados de paciente é registrado no log de auditoria (LGPD).</p>'),
('gerenciar-exames', 'Gerenciar exames e preços', 'Catálogo', 30, 'Editar informações, preços e imagens dos exames.', '<p>Em <strong>Catálogo</strong> ficam os exames oferecidos:</p><ol><li>Busque o exame pelo nome.</li><li>Edite descrição, preço e imagem.</li></ol><p>A maior parte do catálogo vem do Shift pela sincronização — veja o tutorial de integração.</p>'),
('catalogo-shift', 'Catálogo do Shift', 'Catálogo', 31, 'Como o catálogo se relaciona com o sistema laboratorial Shift.', '<p>Os exames, unidades e convênios são importados do <strong>Shift</strong> (sistema laboratorial).</p><p>Você não precisa digitar tudo à mão: a sincronização traz os dados atualizados. Ajustes finos (imagem, texto de vitrine) você faz aqui no painel.</p>'),
('cadastrar-unidades-horarios', 'Unidades e horários de funcionamento', 'Unidades', 35, 'Cadastrar unidades e definir os horários que abrem a agenda.', '<p>Em <strong>Unidades</strong> você gerencia os locais de atendimento:</p><ol><li>Edite endereço e dados de contato de cada unidade.</li><li>Defina os <strong>horários de funcionamento</strong> por dia da semana.</li></ol><p><strong>Importante:</strong> a agenda de cada unidade segue exatamente esses horários — o paciente só consegue agendar dentro do que estiver aberto na unidade escolhida.</p>'),
('gerenciar-convenios', 'Convênios e planos', 'Convênios', 40, 'Manter a lista de convênios e seus planos.', '<p>Em <strong>Convênios</strong> ficam os convênios aceitos e seus planos.</p><p>Assim como o catálogo, os convênios vêm do Shift pela sincronização. Aqui você confere e organiza o que aparece para o paciente.</p>'),
('agendamento-convenio', 'Como funciona o agendamento por convênio', 'Convênios', 41, 'As regras específicas do fluxo de convênio.', '<p>No agendamento por convênio, algumas regras mudam em relação ao particular:</p><ul><li>Não são exibidos preços.</li><li>O paciente informa o convênio e o plano.</li><li>Podem valer regras próprias de antecedência e de unidades disponíveis.</li></ul><p>Os documentos (carteirinha, pedido médico) continuam sendo solicitados no envio.</p>'),
('editar-paginas-site', 'Editar as páginas do site', 'Site & páginas', 50, 'Alterar textos e blocos das páginas pelo construtor.', '<p>Em <strong>Sites &rarr; Páginas do site</strong> você edita as páginas com o construtor de blocos:</p><ol><li>Abra a página e adicione, remova ou reordene blocos.</li><li>Edite os textos e imagens de cada bloco.</li><li>Salve — as mudanças vão ao ar na hora.</li></ol>'),
('construtor-blocos', 'Construtor de blocos: o que cada bloco faz', 'Site & páginas', 51, 'Os tipos de bloco disponíveis para montar uma página.', '<p>Cada página é montada com blocos. Os principais:</p><ul><li><strong>Hero</strong> — destaque no topo com título e imagem de fundo.</li><li><strong>Texto, Imagem, Vídeo, Espaçador</strong> — conteúdo básico.</li><li><strong>Colunas</strong> — divide em colunas (com texto, imagem, vídeo ou formulário).</li><li><strong>Serviços, FAQ, Depoimentos, Estatísticas, Passos, Linha do tempo, Equipe</strong> — seções prontas.</li><li><strong>Banner com atalhos, Busca de exame, Unidades, Convênios</strong> — blocos específicos da Sancet.</li></ul>'),
('escolher-home', 'Definir a página inicial (Home)', 'Site & páginas', 52, 'Escolher qual página abre em primeiro lugar no site.', '<p>Você decide qual página é a inicial:</p><ol><li>Em <strong>Sites &rarr; Páginas do site</strong>, marque a <strong>estrela</strong> na página desejada.</li><li>Só uma página pode ser a Home por vez.</li><li>Se nenhuma estiver marcada, o site usa a home padrão do sistema.</li></ol>'),
('menu-slugs-rodape', 'Ordem do menu, endereços (slugs) e rodapé', 'Site & páginas', 53, 'Reordenar o menu, mudar o endereço das páginas e editar o rodapé.', '<p>Ainda em Sites você pode:</p><ul><li>Reordenar os itens do <strong>menu</strong>.</li><li>Mudar o <strong>slug</strong> (o final do endereço, ex.: /quem-somos) de cada página.</li><li>Editar os textos e links do <strong>rodapé</strong>.</li></ul><p>As cores do rodapé ficam em Configurações &rarr; Aparência.</p>'),
('landing-pages', 'Landing pages promocionais', 'Site & páginas', 54, 'Criar páginas de campanha separadas do site principal.', '<p>Em <strong>Sites &rarr; Landing pages</strong> você cria páginas de campanha (promoções, datas especiais) usando os mesmos blocos, com endereço próprio, sem alterar o site institucional.</p>'),
('banner-atalhos', 'Banner com atalhos na home', 'Site & páginas', 55, 'O bloco de destaque com botões de atalho e imagem.', '<p>O bloco <strong>Banner com atalhos</strong> reproduz o destaque da home: título em degradê, botões de atalho com ícone e imagem ao lado.</p><ul><li>Cada atalho é um botão editável (texto, ícone e link).</li><li>Dá para ajustar a cor de fundo e o tamanho da imagem.</li><li>Há opção de ocultar o card quando quiser.</li></ul>'),
('blog', 'Blog: criar e publicar posts', 'Site & páginas', 56, 'Escrever artigos e controlar o que fica publicado.', '<p>Em <strong>Sites &rarr; Blog</strong>:</p><ol><li>Clique em <strong>Novo post</strong>.</li><li>Preencha título, categoria, resumo e conteúdo.</li><li>Use o interruptor <strong>Publicado</strong> para deixar o post visível ou como rascunho.</li></ol>'),
('aparencia-cores-logo', 'Aparência: cores, logo, favicon e rodapé', 'Configurações', 60, 'Controlar a identidade visual de todo o sistema e do site.', '<p>Em <strong>Configurações &rarr; Aparência</strong> você controla a identidade visual:</p><ul><li><strong>Cores</strong> — cor principal, cor da barra lateral e secundária, aplicadas em todo o sistema e site.</li><li><strong>Logo</strong> — versões clara e escura.</li><li><strong>Favicon</strong> — o ícone da aba do navegador.</li><li><strong>Rodapé</strong> — cores do rodapé.</li></ul><p>As mudanças valem para o site público e para o painel.</p>'),
('email-resend', 'E-mail: remetente e destinatários', 'Configurações', 61, 'Configurar os e-mails automáticos de pedido novo e confirmado.', '<p>Em <strong>Configurações</strong> você define os e-mails transacionais (pedido novo e confirmado):</p><ul><li>O endereço <strong>remetente</strong> (from).</li><li>Os <strong>destinatários</strong> internos que recebem aviso de pedido.</li></ul><p><strong>Atenção:</strong> para enviar a pacientes de verdade, o remetente precisa usar um domínio verificado. O endereço de teste só envia para e-mails já verificados na conta.</p>'),
('sincronizar-shift', 'Sincronizar o catálogo com o Shift', 'Integrações', 65, 'Atualizar exames, unidades e convênios a partir do Shift.', '<p>A sincronização fica em <strong>Configurações</strong> (acesso de administrador):</p><ol><li>Abra a seção de <strong>Sincronização do Shift</strong>.</li><li>Escolha o que sincronizar (exames, unidades, convênios).</li><li>Aguarde a confirmação — o catálogo do site é atualizado.</li></ol><p>Prefira sincronizar fora do horário de pico.</p>'),
('ia-leitura-receita', 'IA: leitura de receita médica', 'Integrações', 66, 'Como o sistema lê a foto da receita para agilizar o pedido.', '<p>O sistema usa inteligência artificial para <strong>ler a foto da receita médica</strong> enviada pelo paciente e sugerir os exames automaticamente.</p><p>Isso acelera o agendamento e reduz erros de digitação. A equipe sempre confere o resultado antes de confirmar o pedido.</p>'),
('equipe-membros-permissoes', 'Adicionar membros e definir permissões', 'Equipe', 70, 'Criar acessos para a equipe e escolher o que cada um pode fazer.', '<p>Em <strong>Equipe</strong> (só administradores):</p><ol><li>Adicione um novo membro pelo e-mail.</li><li>Defina se é <strong>administrador</strong> ou <strong>equipe</strong>.</li><li>Ajuste as permissões por módulo (pedidos, pacientes, catálogo, etc.).</li></ol>'),
('vincular-unidades-usuario', 'Vincular unidades a um usuário', 'Equipe', 71, 'Restringir um membro a ver apenas as unidades dele.', '<p>Você pode limitar um membro da equipe a determinadas unidades:</p><ol><li>Abra o membro em <strong>Equipe</strong>.</li><li>Selecione as unidades a que ele terá acesso.</li></ol><p>Assim, cada recepção enxerga apenas os pedidos da sua unidade.</p>'),
('auditoria-lgpd', 'Log de auditoria de acesso (LGPD)', 'Segurança & LGPD', 80, 'Onde ver o registro de quem acessou dados de pacientes.', '<p>Em <strong>Configurações &rarr; Auditoria (LGPD)</strong> fica o registro de acessos a dados de paciente.</p><p>Cada consulta a um cadastro é registrada, atendendo à LGPD e permitindo rastrear quem viu o quê e quando.</p>'),
('retencao-exclusao-documentos', 'Retenção e exclusão de documentos', 'Segurança & LGPD', 81, 'Como tratar os documentos enviados pelos pacientes.', '<p>Os documentos enviados (RG, pedido médico, etc.) ficam armazenados de forma privada, acessíveis só à equipe.</p><ul><li>O administrador pode <strong>excluir</strong> um documento quando solicitado.</li><li>Laudos e resultados têm prazo legal de guarda — não exclua sem confirmar a regra aplicável.</li></ul>')
on conflict (slug) do nothing;
